### ISSUE TITLE
can you upload database in this .. so that i can import it . 

### ISSUE THREAD

**Issue by surenkl** [namkhanh164/fyp-crawler#1]
i couldn't manage to create the same table to as the u did .. and the coding not running ...

**Comment by eriknguyen** [comment]
This repo was part of the school project and is now no longer maintained. Please feel free to explore by yourself and use this as a reference. 

For the table, you can get some clues from [this Entities source files](https://github.com/eriknguyen/forum-crawler/tree/master/src/Entities)
